// generated from folio-export-common/schemas/bursar-export/bursarExportJob.json
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Bursar export job schema
 */
export interface BursarExportJobDTO {
  /**
   * Filter for bursar export job
   */
  filter:
    | BursarExportFilterAge
    | BursarExportFilterAmount
    | BursarExportFilterFeeType
    | BursarExportFilterLocation
    | BursarExportFilterPatronGroup
    | BursarExportFilterServicePoint
    | BursarExportFilterCondition
    | BursarExportFilterNegation
    | BursarExportFilterPass
    | BursarExportFilterFeeFineOwner;
  groupByPatron: boolean;
  groupByPatronFilter?: BursarExportFilterAggregate;
  header: (
    | BursarExportTokenAggregate
    | BursarExportTokenConstant
    | BursarExportTokenCurrentDate
  )[];
  data: (
    | BursarExportTokenAggregate
    | BursarExportTokenConstant
    | BursarExportTokenCurrentDate
    | BursarExportTokenFeeDate
    | BursarExportTokenFeeAmount
    | BursarExportTokenFeeMetadata
    | BursarExportTokenItemData
    | BursarExportTokenUserData
    | BursarExportTokenUserDataOptional
    | BursarExportTokenConditional
  )[];
  footer: (
    | BursarExportTokenAggregate
    | BursarExportTokenConstant
    | BursarExportTokenCurrentDate
  )[];
  transferInfo: BursarExportTransferCriteria;
}
/**
 * Filter by fees older than certain number of days
 */
export interface BursarExportFilterAge {
  type: string;
  numDays: number;
}
/**
 * Filter by fee amount
 */
export interface BursarExportFilterAmount {
  type: string;
  amount: number;
  condition:
    | 'LESS_THAN_EQUAL'
    | 'LESS_THAN'
    | 'GREATER_THAN'
    | 'GREATER_THAN_EQUAL';
}
/**
 * Filter by fee type
 */
export interface BursarExportFilterFeeType {
  type: string;
  feeFineTypeId: string;
}
/**
 * Filter by location
 */
export interface BursarExportFilterLocation {
  type: string;
  locationId: string;
}
/**
 * Filter by patron group
 */
export interface BursarExportFilterPatronGroup {
  type: string;
  patronGroupId: string;
}
/**
 * Filter by service point
 */
export interface BursarExportFilterServicePoint {
  type: string;
  servicePointId: string;
}
/**
 * Filter conditional operations
 */
export interface BursarExportFilterCondition {
  type: string;
  operation: 'AND' | 'OR';
  criteria: (
    | BursarExportFilterAge
    | BursarExportFilterAmount
    | BursarExportFilterFeeType
    | BursarExportFilterLocation
    | BursarExportFilterPatronGroup
    | BursarExportFilterServicePoint
    | BursarExportFilterCondition
    | BursarExportFilterNegation
    | BursarExportFilterPass
    | BursarExportFilterFeeFineOwner
  )[];
}
/**
 * Negation of filter for bursar export
 */
export interface BursarExportFilterNegation {
  type: string;
  /**
   * Filter for bursar export job
   */
  criteria:
    | BursarExportFilterAge
    | BursarExportFilterAmount
    | BursarExportFilterFeeType
    | BursarExportFilterLocation
    | BursarExportFilterPatronGroup
    | BursarExportFilterServicePoint
    | BursarExportFilterCondition
    | BursarExportFilterNegation
    | BursarExportFilterPass
    | BursarExportFilterFeeFineOwner;
}
/**
 * Filter that is always true
 */
export interface BursarExportFilterPass {
  type: string;
}
/**
 * Filter by fee fine owner
 */
export interface BursarExportFilterFeeFineOwner {
  type: string;
  feeFineOwner: string;
}
/**
 * Filter by aggregate data
 */
export interface BursarExportFilterAggregate {
  type: string;
  property: 'NUM_ROWS' | 'TOTAL_AMOUNT';
  amount: number;
  condition:
    | 'LESS_THAN_EQUAL'
    | 'LESS_THAN'
    | 'GREATER_THAN'
    | 'GREATER_THAN_EQUAL';
}
/**
 * Token to represent aggregated result of multiple fees
 */
export interface BursarExportTokenAggregate {
  type: string;
  value: 'NUM_ROWS' | 'TOTAL_AMOUNT';
  /**
   * only applicable for total amount
   */
  decimal: boolean;
  lengthControl?: BursarExportTokenLengthControl;
}
/**
 * Token to fill in the length of another token
 */
export interface BursarExportTokenLengthControl {
  character: string;
  length: number;
  direction: 'FRONT' | 'BACK';
  truncate: boolean;
}
/**
 * Token to represent a constant used as an arbitrary string
 */
export interface BursarExportTokenConstant {
  type: string;
  value: string;
}
/**
 * Token to represent part of date
 */
export interface BursarExportTokenCurrentDate {
  type: string;
  /**
   * Schema to represent the type of date information
   */
  value:
    | 'YEAR_LONG'
    | 'YEAR_SHORT'
    | 'MONTH'
    | 'DATE'
    | 'HOUR'
    | 'MINUTE'
    | 'SECOND'
    | 'QUARTER'
    | 'WEEK_OF_YEAR_ISO'
    | 'WEEK_YEAR_ISO';
  timezone: string;
  lengthControl?: BursarExportTokenLengthControl;
}
/**
 * Token to represent part of date about a fee
 */
export interface BursarExportTokenFeeDate {
  type: string;
  property: 'CREATED' | 'UPDATED' | 'DUE' | 'RETURNED';
  /**
   * Schema to represent the type of date information
   */
  value:
    | 'YEAR_LONG'
    | 'YEAR_SHORT'
    | 'MONTH'
    | 'DATE'
    | 'HOUR'
    | 'MINUTE'
    | 'SECOND'
    | 'QUARTER'
    | 'WEEK_OF_YEAR_ISO'
    | 'WEEK_YEAR_ISO';
  placeholder: string;
  timezone: string;
  lengthControl?: BursarExportTokenLengthControl;
}
/**
 * Token to represent fee amount
 */
export interface BursarExportTokenFeeAmount {
  type: string;
  decimal: boolean;
  lengthControl?: BursarExportTokenLengthControl;
}
/**
 * Token to represent fee metadata
 */
export interface BursarExportTokenFeeMetadata {
  type: string;
  value: 'FEE_FINE_TYPE_ID' | 'FEE_FINE_TYPE_NAME';
  lengthControl?: BursarExportTokenLengthControl;
}
/**
 * Token to represent item data
 */
export interface BursarExportTokenItemData {
  type: string;
  value:
    | 'BARCODE'
    | 'NAME'
    | 'MATERIAL_TYPE'
    | 'INSTITUTION_ID'
    | 'CAMPUS_ID'
    | 'LIBRARY_ID'
    | 'LOCATION_ID';
  placeholder: string;
  lengthControl?: BursarExportTokenLengthControl;
}
/**
 * Token to represent user data
 */
export interface BursarExportTokenUserData {
  type: string;
  value: 'FOLIO_ID' | 'PATRON_GROUP_ID' | 'EXTERNAL_SYSTEM_ID';
  lengthControl?: BursarExportTokenLengthControl;
}
/**
 * Token to represent optional user data
 */
export interface BursarExportTokenUserDataOptional {
  type: string;
  value: 'BARCODE' | 'USERNAME' | 'FIRST_NAME' | 'MIDDLE_NAME' | 'LAST_NAME';
  placeholder: string;
  lengthControl?: BursarExportTokenLengthControl;
}
/**
 * Token to represent other data tokens depending on certain conditions
 */
export interface BursarExportTokenConditional {
  type: string;
  conditions: {
    /**
     * Filter for bursar export job
     */
    condition:
      | BursarExportFilterAge
      | BursarExportFilterAmount
      | BursarExportFilterFeeType
      | BursarExportFilterLocation
      | BursarExportFilterPatronGroup
      | BursarExportFilterServicePoint
      | BursarExportFilterCondition
      | BursarExportFilterNegation
      | BursarExportFilterPass
      | BursarExportFilterFeeFineOwner;
    /**
     * Usable token for bursar export
     */
    value:
      | BursarExportTokenAggregate
      | BursarExportTokenConstant
      | BursarExportTokenCurrentDate
      | BursarExportTokenFeeDate
      | BursarExportTokenFeeAmount
      | BursarExportTokenFeeMetadata
      | BursarExportTokenItemData
      | BursarExportTokenUserData
      | BursarExportTokenUserDataOptional
      | BursarExportTokenConditional;
    [k: string]: unknown;
  }[];
  /**
   * Usable token for bursar export
   */
  else:
    | BursarExportTokenAggregate
    | BursarExportTokenConstant
    | BursarExportTokenCurrentDate
    | BursarExportTokenFeeDate
    | BursarExportTokenFeeAmount
    | BursarExportTokenFeeMetadata
    | BursarExportTokenItemData
    | BursarExportTokenUserData
    | BursarExportTokenUserDataOptional
    | BursarExportTokenConditional;
}
/**
 * Transfer criteria
 */
export interface BursarExportTransferCriteria {
  conditions: {
    /**
     * Filter for bursar export job
     */
    condition?:
      | BursarExportFilterAge
      | BursarExportFilterAmount
      | BursarExportFilterFeeType
      | BursarExportFilterLocation
      | BursarExportFilterPatronGroup
      | BursarExportFilterServicePoint
      | BursarExportFilterCondition
      | BursarExportFilterNegation
      | BursarExportFilterPass
      | BursarExportFilterFeeFineOwner;
    account: string;
  }[];
  /**
   * account to transfer fees/fines that do not meet any specified conditions to
   */
  else: {
    account?: string;
    [k: string]: unknown;
  };
}
